[server]
headless = true
fileWatcherType = "auto"
enableStaticServing = false

[theme]
base = "light"

[[pages]]
path = "pages/1_Home.py"
name = "Home"

[[pages]]
path = "pages/2_Komparatif Analisis.py"
name = "Komparatif Analisis"
